[project]
name = "uv-test"
version = "0.1.0"
description = "A test project for uv"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.4.0",
    "click>=8.3.1",
    "httpx>=0.28.1",
    "jupyterlab>=4.5.3",
    "rich>=14.3.2",
]
